-- Add accessCode, isActive, usedAt columns to bolsistas table
ALTER TABLE bolsistas 
ADD COLUMN accessCode VARCHAR(50) NOT NULL UNIQUE,
ADD COLUMN isActive BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN usedAt TIMESTAMP NULL,
ADD COLUMN updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
MODIFY userId INT NULL,
MODIFY email VARCHAR(320) NULL;
